// Generated by fca
// fca generate Product --methods=get,getList,create,update,delete,watchList --data

import '../../domain/entities/product/product.dart';
import '../../domain/repositories/product_repository.dart';
import '../data_sources/product/product_data_source.dart';

class DataProductRepository implements ProductRepository {
  final ProductDataSource _dataSource;

  DataProductRepository(this._dataSource);

  @override
  Future<Product> get(String id) {
    return _dataSource.get(id);
  }

  @override
  Future<List<Product>> getList() {
    return _dataSource.getList();
  }

  @override
  Future<Product> create(Product product) {
    return _dataSource.create(product);
  }

  @override
  Future<Product> update(Product product) {
    return _dataSource.update(product);
  }

  @override
  Future<void> delete(String id) {
    return _dataSource.delete(id);
  }

  @override
  Stream<List<Product>> watchList() {
    return _dataSource.watchList();
  }
}
