include: package:pedantic/analysis_options.yaml
linter:
  rules:
    library_names: true
    avoid_empty_else: true
    unecessary_const: true
    unawaited_futures: false
analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
enable-experiment:
  - extension-methods