// Generated by fca

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import '../../repositories/product_repository.dart';

class DeleteProductUseCase extends CompletableUseCase<String> {
  final ProductRepository _repository;

  DeleteProductUseCase(this._repository);

  @override
  Future<void> execute(String id, CancelToken? cancelToken) async {
    cancelToken?.throwIfCancelled();
    return _repository.delete(id);
  }
}
