// Generated by fca

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import '../../entities/product/product.dart';
import '../../repositories/product_repository.dart';

class GetProductListUseCase extends UseCase<List<Product>, NoParams> {
  final ProductRepository _repository;

  GetProductListUseCase(this._repository);

  @override
  Future<List<Product>> execute(NoParams params, CancelToken? cancelToken) async {
    cancelToken?.throwIfCancelled();
    return _repository.getList();
  }
}
