// Generated by fca

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import '../../entities/product/product.dart';
import '../../repositories/product_repository.dart';

class UpdateProductUseCase extends UseCase<Product, Product> {
  final ProductRepository _repository;

  UpdateProductUseCase(this._repository);

  @override
  Future<Product> execute(Product product, CancelToken? cancelToken) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(product);
  }
}
