// Generated by fca

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import '../../entities/product/product.dart';
import '../../repositories/product_repository.dart';

class WatchProductListUseCase extends StreamUseCase<List<Product>, NoParams> {
  final ProductRepository _repository;

  WatchProductListUseCase(this._repository);

  @override
  Stream<List<Product>> execute(NoParams params, CancelToken? cancelToken) {
    return _repository.watchList();
  }
}
