// Generated by fca
// fca generate Product --methods=get,getList,create,update,delete,watchList --vpc

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import 'product_presenter.dart';

class ProductController extends Controller {
  final ProductPresenter _presenter;

  ProductController(this._presenter);

  @override
  void onDisposed() {
    _presenter.dispose();
    super.onDisposed();
  }
}
