// Generated by fca
// fca generate Product --methods=get,getList,create,update,delete,watchList --vpc
// ignore_for_file: no_logic_in_create_state

import 'package:flutter/material.dart';
import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import '../../domain/repositories/product_repository.dart';
import 'product_controller.dart';
import 'product_presenter.dart';

class ProductView extends CleanView {
  final ProductRepository productRepository;

  const ProductView({
    super.key,
    super.routeObserver,
    required this.productRepository,
  });

  @override
  State<ProductView> createState() => _ProductViewState(
        ProductController(
          ProductPresenter(
            productRepository: productRepository,
          ),
        ),
      );
}

class _ProductViewState extends CleanViewState<ProductView, ProductController> {
  _ProductViewState(super.controller);

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(
        title: const Text('Product'),
      ),
      body: ControlledWidgetBuilder<ProductController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
