// Generated by fca
// fca generate Product --methods=get,getList,create,update,delete,watchList --vpc

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import '../../domain/entities/product/product.dart';
import '../../domain/repositories/product_repository.dart';
import '../../domain/usecases/product/get_product_usecase.dart';
import '../../domain/usecases/product/get_product_list_usecase.dart';
import '../../domain/usecases/product/create_product_usecase.dart';
import '../../domain/usecases/product/update_product_usecase.dart';
import '../../domain/usecases/product/delete_product_usecase.dart';
import '../../domain/usecases/product/watch_product_list_usecase.dart';

class ProductPresenter extends Presenter {
  final ProductRepository productRepository;

  late final GetProductUseCase _getProduct;
  late final GetProductListUseCase _getProductList;
  late final CreateProductUseCase _createProduct;
  late final UpdateProductUseCase _updateProduct;
  late final DeleteProductUseCase _deleteProduct;
  late final WatchProductListUseCase _watchProductList;

  ProductPresenter({
    required this.productRepository,
  }) {
    _getProduct = registerUseCase(GetProductUseCase(productRepository));
    _getProductList = registerUseCase(GetProductListUseCase(productRepository));
    _createProduct = registerUseCase(CreateProductUseCase(productRepository));
    _updateProduct = registerUseCase(UpdateProductUseCase(productRepository));
    _deleteProduct = registerUseCase(DeleteProductUseCase(productRepository));
    _watchProductList =
        registerUseCase(WatchProductListUseCase(productRepository));
  }

  Future<Result<Product, AppFailure>> getProduct(String id) {
    return execute(_getProduct, id);
  }

  Future<Result<List<Product>, AppFailure>> getProductList() {
    return execute(_getProductList, const NoParams());
  }

  Future<Result<Product, AppFailure>> createProduct(Product product) {
    return execute(_createProduct, product);
  }

  Future<Result<Product, AppFailure>> updateProduct(Product product) {
    return execute(_updateProduct, product);
  }

  Future<Result<void, AppFailure>> deleteProduct(String id) {
    return execute(_deleteProduct, id);
  }

  Stream<Result<List<Product>, AppFailure>> watchProductList() {
    return executeStream(_watchProductList, const NoParams());
  }
}
