// Generated by fca
// fca generate Product --methods=get,getList,create,update,delete,watchList --data

import '../../../domain/entities/product/product.dart';

abstract class ProductDataSource {
  Future<Product> get(String id);
  Future<List<Product>> getList();
  Future<Product> create(Product product);
  Future<Product> update(Product product);
  Future<void> delete(String id);
  Stream<List<Product>> watchList();
}
