name: Quality Assurance

on: [pull_request]

jobs:
  quality-assurance:
    name: Validating health on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configuring java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v1.3.1
        with:
          flutter-version: '1.17.0'
          channel: 'stable'
      - name: Searching for formatting issues
        run: flutter format --set-exit-if-changed .
      - name: Getting dependencies
        run: flutter packages get
      - name: Analyzing files
        run: flutter analyze .
      - name: Running tests
        run: flutter test .